import { Router } from "express";
import { protect } from "../middlewares/authMiddleware.js";
import * as c from "../controllers/marketplace.controller.js";
const router = Router();
router.use(protect);
router.get("/dashboard", c.dashboard);
router.get("/guides/:id/quality", c.guideQuality);
router.get("/trips/:id/edit", c.getEditableTrip);
router.patch("/trips/:id/content", c.editTrip);
router.post("/trips/:id/actions/:action", c.tripAction);
router.post("/revisions/:id/actions/:action", c.revisionAction);
router.post("/occurrences/:id/actions/:action", c.occurrenceAction);
router.post("/bookings/:id/attendance/:action", c.attendanceAction);
router.post("/accounts/:id/actions/:action", c.accountAction);
router.post("/verification/:id/actions/:action", c.verificationAction);
router.post("/reviews/:id/actions/:action", c.reviewAction);
router.get("/reviews/:id", c.reviewDetail);
router.get("/audit/:id", c.auditHistory);
router.post("/cases/:id/resolve", c.resolveCase);
router.get("/cases/:id", c.caseDetail);
router.post("/merchandising/:kind/:id", c.merchandising);
export default router;
